#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

REPO_DIR="${REPO_DIR:-$BASE_DIR/sub2api-main}"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/sub2api.env}"
LD_LIBRARY_PATH_DEFAULT="/home/aias94coffee/.local/libroot/usr/lib/x86_64-linux-gnu"
LD_LIBRARY_PATH_VALUE="${LD_LIBRARY_PATH:-$LD_LIBRARY_PATH_DEFAULT}"

SERVER_HOST_VALUE="${SERVER_HOST:-0.0.0.0}"
SERVER_PORT_VALUE="${SERVER_PORT:-8081}"
SERVER_MODE_VALUE="${SERVER_MODE:-release}"
RUN_MODE_VALUE="${RUN_MODE:-standard}"
TZ_VALUE="${TZ:-Asia/Shanghai}"
DATA_DIR_VALUE="${DATA_DIR:-$REPO_DIR}"

DATABASE_HOST_VALUE="${DATABASE_HOST:-127.0.0.1}"
DATABASE_PORT_VALUE="${DATABASE_PORT:-5432}"
DATABASE_USER_VALUE="${DATABASE_USER:-postgres}"
DATABASE_PASSWORD_VALUE="${DATABASE_PASSWORD:-postgres}"
DATABASE_DBNAME_VALUE="${DATABASE_DBNAME:-sub2api}"
DATABASE_SSLMODE_VALUE="${DATABASE_SSLMODE:-disable}"
REDIS_HOST_VALUE="${REDIS_HOST:-127.0.0.1}"
REDIS_PORT_VALUE="${REDIS_PORT:-6379}"
ADMIN_EMAIL_VALUE="${ADMIN_EMAIL:-admin@sub2api.local}"
ADMIN_PASSWORD_VALUE="${ADMIN_PASSWORD:-}"

cd "$REPO_DIR"
mkdir -p runtime

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

OLD_PID="$(sudo ss -ltnp | grep ":${SERVER_PORT_VALUE} " | grep -o 'pid=[0-9]*' | head -n1 | cut -d= -f2 || true)"
if [[ -n "${OLD_PID:-}" ]]; then
  sudo kill "$OLD_PID" || true
  sleep 2
fi

nohup env \
  LD_LIBRARY_PATH="$LD_LIBRARY_PATH_VALUE" \
  DATA_DIR="$DATA_DIR_VALUE" \
  AUTO_SETUP=true \
  SERVER_HOST="$SERVER_HOST_VALUE" \
  SERVER_PORT="$SERVER_PORT_VALUE" \
  SERVER_MODE="$SERVER_MODE_VALUE" \
  RUN_MODE="$RUN_MODE_VALUE" \
  TZ="$TZ_VALUE" \
  DATABASE_HOST="$DATABASE_HOST_VALUE" \
  DATABASE_PORT="$DATABASE_PORT_VALUE" \
  DATABASE_USER="$DATABASE_USER_VALUE" \
  DATABASE_PASSWORD="$DATABASE_PASSWORD_VALUE" \
  DATABASE_DBNAME="$DATABASE_DBNAME_VALUE" \
  DATABASE_SSLMODE="$DATABASE_SSLMODE_VALUE" \
  REDIS_HOST="$REDIS_HOST_VALUE" \
  REDIS_PORT="$REDIS_PORT_VALUE" \
  TOTP_ENCRYPTION_KEY="${TOTP_ENCRYPTION_KEY:-}" \
  ADMIN_EMAIL="$ADMIN_EMAIL_VALUE" \
  ADMIN_PASSWORD="$ADMIN_PASSWORD_VALUE" \
  ./sub2api > runtime/sub2api-"$SERVER_PORT_VALUE".log 2>&1 &

sleep 6
curl --max-time 15 -sS "http://127.0.0.1:${SERVER_PORT_VALUE}/health"
