import { resolveShellLabelOverrides } from '@/utils/shellLabelOverrides'

export const apiKeysShellLabelKeys = [
  'actions',
  'active',
  'allGroups',
  'allStatus',
  'apiKey',
  'cancel',
  'ccsClientSelectClaudeCode',
  'ccsClientSelectClaudeCodeDesc',
  'ccsClientSelectDescription',
  'ccsClientSelectGeminiCli',
  'ccsClientSelectGeminiCliDesc',
  'ccsClientSelectTitle',
  'ccSwitchNotInstalled',
  'clickToChangeGroup',
  'useKeyModalAntigravityClaudeNote',
  'useKeyModalAntigravityDescription',
  'useKeyModalAntigravityGeminiNote',
  'useKeyModalCliClaudeCode',
  'useKeyModalCliCodexCli',
  'useKeyModalCliCodexCliWs',
  'useKeyModalCliGeminiCli',
  'useKeyModalCliOpencode',
  'useKeyModalCopied',
  'useKeyModalCopy',
  'useKeyModalDescription',
  'useKeyModalGeminiDescription',
  'useKeyModalGeminiModelComment',
  'useKeyModalGeminiNote',
  'useKeyModalNoGroupDescription',
  'useKeyModalNoGroupTitle',
  'useKeyModalNote',
  'useKeyModalOpenAIConfigTomlHint',
  'useKeyModalOpenAIDescription',
  'useKeyModalOpenAINote',
  'useKeyModalOpenAINoteWindows',
  'useKeyModalOpencodeHint',
  'useKeyModalTitle',
  'copyToClipboard',
  'copied',
  'create',
  'createFirstKey',
  'created',
  'createKey',
  'currentExpiration',
  'customDate',
  'customKeyHint',
  'customKeyInvalidChars',
  'customKeyLabel',
  'customKeyPlaceholder',
  'customKeyRequired',
  'customKeyTooShort',
  'delete',
  'deleteConfirmMessage',
  'deleteKey',
  'disable',
  'edit',
  'editKey',
  'endpointClickToCopy',
  'endpointCopied',
  'endpointCopiedHint',
  'endpointDefault',
  'endpointSpeedTest',
  'endpointTitle',
  'enable',
  'expiration',
  'expirationDate',
  'expirationDateHint',
  'expiresInDays',
  'expiresAt',
  'extendDays',
  'failedToChangeGroup',
  'failedToDelete',
  'failedToLoad',
  'failedToResetQuota',
  'failedToResetRateLimit',
  'failedToSave',
  'failedToUpdateStatus',
  'group',
  'groupChangedSuccess',
  'groupLabel',
  'groupRequired',
  'inactive',
  'importToCcSwitch',
  'ipBlacklist',
  'ipBlacklistHint',
  'ipBlacklistPlaceholder',
  'ipRestriction',
  'ipRestrictionEnabled',
  'ipWhitelist',
  'ipWhitelistHint',
  'ipWhitelistPlaceholder',
  'keyCreatedSuccess',
  'keyDeletedSuccess',
  'keyDisabledSuccess',
  'keyEnabledSuccess',
  'keyUpdatedSuccess',
  'lastUsedAt',
  'name',
  'nameLabel',
  'namePlaceholder',
  'noExpiration',
  'noGroup',
  'noGroupFound',
  'noKeysYet',
  'quota',
  'quotaAmountHint',
  'quotaAmountPlaceholder',
  'quotaLimit',
  'quotaResetSuccess',
  'quotaUsed',
  'rateLimitColumn',
  'rateLimitHint',
  'rateLimit1d',
  'rateLimit5h',
  'rateLimit7d',
  'rateLimitResetSuccess',
  'rateLimitSection',
  'refresh',
  'reset',
  'resetQuotaConfirmMessage',
  'resetQuotaTitle',
  'resetQuotaUsed',
  'resetRateLimitConfirmMessage',
  'resetRateLimitTitle',
  'resetRateLimitUsage',
  'resetNow',
  'resetUsage',
  'saving',
  'searchGroup',
  'searchPlaceholder',
  'selectGroup',
  'selectStatus',
  'status',
  'statusActive',
  'statusExpired',
  'statusInactive',
  'statusQuotaExhausted',
  'statusLabel',
  'today',
  'total',
  'update',
  'useKey',
  'usage',
] as const

export type ApiKeysShellLabelKey = typeof apiKeysShellLabelKeys[number]
export type ApiKeysShellLabels = Partial<Record<ApiKeysShellLabelKey, string>>

export function resolveApiKeysShellLabels(raw: string | undefined, runtimeLocale: 'zh' | 'en'): ApiKeysShellLabels {
  const labels = resolveShellLabelOverrides(raw, runtimeLocale, apiKeysShellLabelKeys)
  return Object.fromEntries(
    Object.entries(labels).filter((entry): entry is [ApiKeysShellLabelKey, string] => typeof entry[1] === 'string'),
  )
}

export function renderApiKeysShellText(
  labels: ApiKeysShellLabels,
  key: ApiKeysShellLabelKey,
  params: Record<string, string | number> = {},
): string {
  let value = labels[key] || ''
  for (const [paramKey, paramValue] of Object.entries(params)) {
    value = value.split(`{${paramKey}}`).join(String(paramValue))
  }
  return value
}
